---
galaxy_info:
  author: Ansible Automation
  description: Ansible role for deploying fail2ban protection for Nextcloud
  company: 
  
  license: MIT
  
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - jammy  # 22.04
        - focal  # 20.04
    - name: Debian
      versions:
        - bullseye  # 11
        - bookworm  # 12
  
  galaxy_tags:
    - nextcloud
    - fail2ban
    - security
    - hardening
    - brute-force
    - protection

dependencies: []
