---
galaxy_info:
  author: Ansible Developer
  description: Install and configure sendmail for local email delivery
  company: null
  license: MIT
  min_ansible_version: '2.9'
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
  galaxy_tags:
    - sendmail
    - mail
    - email
    - notifications

dependencies: []
